name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }} ${{ matrix.QT_API }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            QT_API: PySide6
            with_opencl: false
          #- os: ubuntu-22.04
          #  python-version: "3.11"
          #  QT_API: PyQt6
          #  with_opencl: true
          #- os: ubuntu-22.04
          #  python-version: "3.13"
          #  QT_API: PySide6
          #  with_opencl: true

          #- os: macos-13
          #  python-version: "3.12"
          #  QT_API: PyQt5
          #  with_opencl: true
          - os: macos-13
            python-version: "3.13"
            QT_API: PyQt6
            with_opencl: true
          #- os: macos-13
          #  python-version: "3.10"
          #  QT_API: PySide6
          #  with_opencl: true

          #- os: windows-latest
          #  python-version: "3.13"
          #  QT_API: PyQt5
          #  with_opencl: false
          #- os: windows-latest
          #  python-version: "3.10"
          #  QT_API: PyQt6
          #  with_opencl: false
          - os: windows-latest
            python-version: "3.12"
            QT_API: PyQt5
            with_opencl: false

    steps:
      - uses: actions/checkout@v4        
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - uses: ./.github/actions/setup-system
      - name: Set up MSVC environment if applicable
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64  # ou x86 selon vos besoins
      - name: Install build dependencies
        run: |
          pip install --upgrade --pre build wheel 

      - name: Build Windows
        shell: cmd
        if: runner.os == 'Windows'          
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
          echo %PATH%
          python -m build 
          ls dist

      - name: Build Unix
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.9"
        if: runner.os != 'Windows'
        run: |
          python -m build 
          ls dist

      - name: Install
        run: |
          pip install -r ci/requirements-pinned.txt
          pip install --pre "${{ matrix.QT_API }}"
          pip install --pre "$(ls dist/silx*.whl)[full,test]"
          python ./ci/info_platform.py
          pip list

      - name: Test
        env:
          QT_API: ${{ matrix.QT_API }}
          SILX_TEST_LOW_MEM: "False"
          SILX_OPENCL: ${{ matrix.with_opencl && 'True' || 'False' }}
        run: |
          python run_tests.py --installed --qt-binding=${{ matrix.QT_API }}
